spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sumin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    CREATE database instagram DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
    username: root
    password: root