spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: <gmail id>
    password: <password>
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    default-encoding: UTF-8
